version: '3'

services:
    db:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - 3306:3306
    frontend:
        image: 'node'
        volumes:
            - "./frontend:/frontend"
        ports:
            - 1024:1024
        command: "/bin/sh -c '(cd /frontend; npm install; npm start)'"
#    backend: not yet.
